Repository WildCodeSchool/orleans-php-202103-project-tempsloisirs, pull requests merged in 2021-04, with the labels that each got.

#31 Merge S01US04_adminCA to dev
  README.md
  public/assets/css/admin.css
  public/assets/css/style.css
  src/Controller/AdminBoardController.php
  src/Model/AdminBoardManager.php
  src/View/Admin/Board/index.html.twig
  src/View/layout.html.twig
  temps_des_loisirs.sql
Labels: Corrections done, Reviewed

#70 changed each responsive cards sizes
  src/View/Admin/Board/index.html.twig
Labels: Corrections done, Reviewed

#39 S01 us02 admin activities
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/Admin/Activity/index.html.twig
  temps_des_loisirs.sql
Labels: Corrections done, Reviewed

#40 S01US01_nav to dev
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/favicon.png
  public/assets/images/faviconTL.ico
  public/assets/images/faviconTL.png
  src/Controller/HomeController.php
  src/View/Admin/Board/index.html.twig
  src/View/Components/_navbarAdmin.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#43 S01US08_addAdminCA to dev
  src/Controller/AdminBoardController.php
  src/Model/AdminBoardManager.php
  src/View/Admin/Board/_form.html.twig
  src/View/Admin/Board/add.html.twig
  temps_des_loisirs.sql
Labels: Corrections done, Reviewed

#41 S01 us09 admin home
  src/Controller/AdminController.php
  src/View/Admin/home.html.twig
Labels: Corrections done, Reviewed

#74 S01US06_deleteAdminCA to dev
  src/Controller/AdminBoardController.php
  src/View/Admin/Board/index.html.twig
Labels: Conflicts, Conflicts resolved, Reviewed

#38 US 3 Creation of controller and views for the events management
  public/assets/css/adminEvents.css
  public/assets/css/style.css
  public/assets/images/favicon.ico
  simple-mvc.sql
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/Event/index.html.twig
  src/View/layout.html.twig
  temps_des_loisirs.sql
Labels: Conflicts, Conflicts resolved, Reviewed

#78 S02US07_editAdminCA
  src/Controller/AdminBoardController.php
  src/Model/AdminBoardManager.php
  src/View/Admin/Board/_form.html.twig
  src/View/Admin/Board/edit.html.twig
Labels: Conflicts, Conflicts resolved, Reviewed

#88 S02 us12 admin activities delete
  src/Controller/AdminActivityController.php
  src/View/Admin/Activity/index.html.twig
Labels: Corrections done, Reviewed

#79 S02US15 Creation of the Add Event Page (form + form validation + model for save events on DB)
  public/assets/css/adminEvents.css
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/index.html.twig
Labels: Corrections done, Reviewed

#90 S02US16_addAdminInfo to dev
  public/assets/css/information.css
  src/Controller/AdminInformationController.php
  src/Model/InformationManager.php
  src/View/Admin/Information/_form.html.twig
  src/View/Admin/Information/add.html.twig
  temps_des_loisirs.sql
Labels: Reviewed

#95 FIX: Renamed button in edit section of Board
  src/View/Admin/Board/_form.html.twig
  src/View/Admin/Board/edit.html.twig
Labels: Reviewed

#92 Dev to master: Sprint 2 version 1
  README.md
  public/assets/css/admin.css
  public/assets/css/adminEvents.css
  public/assets/css/information.css
  public/assets/css/navbar.css
  public/assets/css/style.css
  public/assets/images/favicon.ico
  public/assets/images/favicon.png
  public/assets/images/faviconTL.ico
  public/assets/images/faviconTL.png
  simple-mvc.sql
  src/Controller/AdminActivityController.php
  src/Controller/AdminBoardController.php
  src/Controller/AdminController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminInformationController.php
  src/Controller/HomeController.php
  src/Model/ActivityManager.php
  src/Model/AdminBoardManager.php
  src/Model/EventManager.php
  src/Model/InformationManager.php
  src/View/Admin/Activity/index.html.twig
  src/View/Admin/Board/_form.html.twig
  src/View/Admin/Board/add.html.twig
  src/View/Admin/Board/edit.html.twig
  src/View/Admin/Board/index.html.twig
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Information/_form.html.twig
  src/View/Admin/Information/add.html.twig
  src/View/Admin/home.html.twig
  src/View/Components/_navbarAdmin.html.twig
  src/View/Home/index.html.twig
  src/View/layout.html.twig
  temps_des_loisirs.sql
Labels: Reviewed

#93 FIX: "Retour au menu admin" button on Board index page
  src/View/Admin/Board/index.html.twig
Labels: Reviewed

#96 FIX: Card size in Events
  src/View/Admin/Event/index.html.twig
Labels: Conflicts resolved, Reviewed

#87 S02 us13 admin activities add
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/Admin/Activity/add.html.twig
  src/View/Admin/Activity/index.html.twig
  src/View/Admin/home.html.twig
  src/View/Components/_formAdminActivity.twig
Labels: Corrections done, Reviewed

#82 S02 us10 admin info
  public/assets/css/admin.css
  public/assets/css/information.css
  public/assets/css/style.css
  src/Controller/AdminInformationController.php
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Information/_form.html.twig
  src/View/Admin/Information/index.html.twig
  temps_des_loisirs.sql
Labels: Corrections done, Reviewed

#89 FIX : Navbar Includes
  src/View/Admin/Activity/index.html.twig
  src/View/Admin/Board/add.html.twig
  src/View/Admin/Board/edit.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Components/_navbarAdmin.html.twig
Labels: Reviewed

#98 S02US05_ Nouvelle branch pour DELETE each event
  src/Controller/AdminEventController.php
  src/View/Admin/Event/index.html.twig
Labels: Corrections done, Reviewed

#99 Sprint 2: Dev to Master
  public/assets/css/admin.css
  public/assets/css/information.css
  public/assets/css/style.css
  src/Controller/AdminActivityController.php
  src/Controller/AdminEventController.php
  src/Controller/AdminInformationController.php
  src/Model/ActivityManager.php
  src/View/Admin/Activity/add.html.twig
  src/View/Admin/Activity/index.html.twig
  src/View/Admin/Board/add.html.twig
  src/View/Admin/Board/edit.html.twig
  src/View/Admin/Board/index.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Information/_form.html.twig
  src/View/Admin/Information/index.html.twig
  src/View/Admin/home.html.twig
  src/View/Components/_formAdminActivity.twig
  src/View/Components/_navbarAdmin.html.twig
  temps_des_loisirs.sql
Labels: Reviewed

#100 S02US11 - Nouvelle branch pour UPDATE Events
  src/Controller/AdminEventController.php
  src/Model/EventManager.php
  src/View/Admin/Event/edit.html.twig
  src/View/Admin/Event/index.html.twig
Labels: Corrections done, Reviewed

#97 FIX : Footer Layout Admin
  public/assets/css/admin.css
  src/View/Admin/Activity/add.html.twig
  src/View/Admin/Activity/index.html.twig
  src/View/Admin/Board/add.html.twig
  src/View/Admin/Board/edit.html.twig
  src/View/Admin/Board/index.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/edit.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Information/add.html.twig
  src/View/Admin/Information/index.html.twig
  src/View/Components/_navbarAdmin.html.twig
  src/View/layout.html.twig
  src/View/layoutAdmin.html.twig
Labels: Corrections done, Reviewed

#143 S02 us14 admin activities edit
  src/Controller/AdminActivityController.php
  src/Controller/AdminController.php
  src/Model/ActivityManager.php
  src/View/Admin/Activity/_form.html.twig
  src/View/Admin/Activity/edit.html.twig
  src/View/Admin/Activity/index.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/show.html.twig
Labels: Corrections done, Reviewed

#146 S02 us17 edit admin info
  src/Controller/AdminInformationController.php
  src/Model/InformationManager.php
  src/View/Admin/Information/_form.html.twig
  src/View/Admin/Information/edit.html.twig
  src/View/Admin/Information/index.html.twig
Labels: Corrections done, Reviewed

#147 S03US21_Navbar to dev
  src/View/Components/_navbar.html.twig
Labels: Reviewed

#148 S02US25_deleteAdminInfo: ajout de la methode delete dans le controller
  src/Controller/AdminInformationController.php
  src/View/Admin/Information/index.html.twig
Labels: Conflicts resolved, Reviewed

#149 S03US26_aboutHistory
  public/assets/css/about.css
  public/assets/css/style.css
  src/Controller/AboutController.php
  src/View/About/index.html.twig
Labels: Corrections done, Reviewed

#172 S02 us14 admin activity edit new
  src/Controller/AdminActivityController.php
  src/Model/ActivityManager.php
  src/View/Admin/Activity/edit.html.twig
  src/View/Admin/Activity/index.html.twig
Labels: Reviews requested

#174 Restore
  public/assets/css/about.css
  public/assets/css/style.css
  src/Controller/AboutController.php
  src/Controller/AdminActivityController.php
  src/Controller/AdminController.php
  src/Controller/AdminInformationController.php
  src/Model/ActivityManager.php
  src/Model/InformationManager.php
  src/View/About/index.html.twig
  src/View/Admin/Activity/_form.html.twig
  src/View/Admin/Activity/edit.html.twig
  src/View/Admin/Information/_form.html.twig
  src/View/Admin/Information/edit.html.twig
  src/View/Admin/Information/index.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Item/edit.html.twig
  src/View/Item/show.html.twig
  temps_des_loisirs.sql
Labels: Reviews requested

#177 FIX: updated path in activity form
  src/View/Admin/Activity/add.html.twig
  src/View/Admin/Activity/edit.html.twig
Labels: Reviewed

#178 S03US27_aboutTimeline to dev
  public/assets/css/about.css
  public/assets/css/style.css
  src/View/About/index.html.twig
  src/View/layout.html.twig
Labels: Reviewed

#151 S03 us20 display activities
  public/assets/css/activity.css
  public/assets/images/icon_time.svg.png
  public/assets/images/no-img.png
  src/Controller/ActivityController.php
  src/View/Home/activity.html.twig
Labels: Corrections done, Reviewed

#180 FIX_spacing_and_sizing_AdminHome
  src/View/Admin/home.html.twig
Labels: Reviewed

#181 FIX: Harmonised Event form with rest of website
  public/assets/css/adminEvents.css
  src/View/Admin/Event/_form.html.twig
Labels: Reviewed
