Repository WildCodeSchool/orleans-php-202103-project-tempsloisirs, pull requests merged in 2021-05, with the labels that each got.

#206 S04US28_aboutBoard to Dev
  public/assets/css/about.css
  src/Controller/AboutController.php
  src/Controller/AdminBoardController.php
  src/Model/BoardManager.php
  src/View/About/index.html.twig
Labels: Reviewed

#201 S03US29 Footer (Footer creation. Insert into layout as a component)
  public/assets/css/footer.css
  src/View/Components/_footer.html.twig
  src/View/layout.html.twig
Labels: Corrections done, Reviewed

#169 S3 us17 create tables: photo and album
  temps_des_loisirs.sql
Labels: Corrections done, Reviewed

#207 S04US31_aboutJoin to Dev
  public/assets/css/about.css
  src/View/About/index.html.twig
Labels: Reviewed

#179 S03US19 Events page from the new Dev folder (to avoid conflicts)
  public/assets/css/event.css
  public/assets/css/style.css
  public/assets/images/event/bingo.jpg
  public/assets/images/event/sortis.jpg
  public/assets/images/event/voyages.jpg
  src/Controller/EventController.php
  src/Model/EventManager.php
  src/View/Home/event.html.twig
Labels: Reviewed

#209 FIX Footer (Deleting media screen that was causing problems)
  public/assets/css/footer.css
Labels: Reviewed

#212 Sprint4 Dev to Master 1
  public/assets/css/about.css
  public/assets/css/activity.css
  public/assets/css/event.css
  public/assets/css/footer.css
  public/assets/css/style.css
  public/assets/images/event/bingo.jpg
  public/assets/images/event/sortis.jpg
  public/assets/images/event/voyages.jpg
  src/Controller/AboutController.php
  src/Controller/ActivityController.php
  src/Controller/AdminBoardController.php
  src/Controller/EventController.php
  src/Model/BoardManager.php
  src/Model/EventManager.php
  src/View/About/index.html.twig
  src/View/Components/_footer.html.twig
  src/View/Home/activity.html.twig
  src/View/Home/event.html.twig
  src/View/layout.html.twig
  temps_des_loisirs.sql
Labels: Reviewed

#213 FIX_nav_links
  src/View/Components/_navbar.html.twig
Labels: Reviewed

#215 FIX_add_button_adminHome
  src/View/Admin/home.html.twig
Labels: Reviewed, Reviews requested

#216 FIX_icons_info_types
  src/Controller/AdminInformationController.php
Labels: Reviewed

#217 FIX_spacing_h1_activity
  src/View/Home/activity.html.twig
Labels: Reviewed

#221 FIX_if_events_is_empty
  src/View/Home/event.html.twig
Labels: Reviewed

#222 FIX - Fixing the links for footer navbar
  src/View/Components/_footer.html.twig
Labels: Reviewed

#223 FIX: Time format in form
  src/View/Admin/Activity/_form.html.twig
Labels: Reviewed

#224 FIX | Activity Page - Carousel size
  public/assets/css/activity.css
Labels: Reviewed

#208 S03US32 Page d'Accueil complète
  public/assets/css/home.css
  public/assets/images/home/heroimage.jpg
  src/Controller/HomeController.php
  src/View/Admin/Information/index.html.twig
  src/View/Home/index.html.twig
  src/View/Home/informations.html.twig
Labels: Corrections done, Reviewed

#219 FIX: Activity time display is more user friendly. Displaying end time too
  public/assets/css/activity.css
  src/View/Home/activity.html.twig
Labels: Corrections done, Reviewed

#205 S03US11_contact ajout du backend pour le contact
  public/assets/css/contact.css
  public/assets/css/thanks.css
  src/Controller/ContactController.php
  src/View/Contact/_form.html.twig
  src/View/Contact/index.html.twig
  src/View/Contact/thanks.html.twig
Labels: Corrections done, Reviewed

#225 S04 dev to Master 2
  public/assets/css/activity.css
  public/assets/css/contact.css
  public/assets/css/home.css
  public/assets/css/thanks.css
  public/assets/images/home/heroimage.jpg
  src/Controller/AdminInformationController.php
  src/Controller/ContactController.php
  src/Controller/HomeController.php
  src/View/Admin/Activity/_form.html.twig
  src/View/Admin/Information/index.html.twig
  src/View/Admin/home.html.twig
  src/View/Components/_footer.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Contact/_form.html.twig
  src/View/Contact/index.html.twig
  src/View/Contact/thanks.html.twig
  src/View/Home/activity.html.twig
  src/View/Home/event.html.twig
  src/View/Home/index.html.twig
  src/View/Home/informations.html.twig
Labels: Reviewed

#227 FIX: ajout du liens sur le bouton contact
  src/View/About/index.html.twig
Labels: Reviewed

#228 FIX logo link nav
  src/View/Components/_navbar.html.twig
Labels: Reviewed

#240 fix page accueil (elements info et events du mois)
  public/assets/css/home.css
  src/View/Home/index.html.twig
Labels: Reviewed

#244 FIX: Uniformisation des pages du Panel Admin, Forms, Spacing, Size, Responsive, Redirection
  public/assets/css/adminEvents.css
  src/View/Admin/Activity/_form.html.twig
  src/View/Admin/Activity/add.html.twig
  src/View/Admin/Activity/edit.html.twig
  src/View/Admin/Activity/index.html.twig
  src/View/Admin/Board/_form.html.twig
  src/View/Admin/Board/index.html.twig
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/edit.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Information/_form.html.twig
  src/View/Admin/Information/index.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed

#241 FIX: contact
  src/Controller/ContactController.php
  src/View/Contact/_form.html.twig
  src/View/Contact/index.html.twig
Labels: Reviewed

#247 FIX: text activity centré
  src/View/Home/activity.html.twig
Labels: Reviewed

#249 FIX: fix de la synthaxe du text d'après le groupe haras
  src/View/About/index.html.twig
Labels: Reviewed

#248 FIX - Contact page - Deleting default link from openmaps, adjusting css from index.html
  public/assets/css/contact.css
  src/View/Contact/index.html.twig
Labels: Reviewed

#250 FIX: Alternative message if no activity
  src/View/Home/activity.html.twig
Labels: Reviewed

#251 Fix_responsive_contact
  public/assets/css/thanks.css
  src/View/Contact/_form.html.twig
  src/View/Contact/index.html.twig
  src/View/Contact/thanks.html.twig
  src/View/Home/activity.html.twig
Labels: Reviewed

#252 FIX Information page
  public/assets/css/listinfo.css
  src/View/Home/index.html.twig
  src/View/Home/informations.html.twig
Labels: Reviewed

#253 FIX: rajout d'une phrase dans le thanks pour la santé psychologique d'Emma
  src/View/Contact/thanks.html.twig
Labels: Reviewed

#254 fix margin LastInfos
  public/assets/css/home.css
  src/View/Home/index.html.twig
Labels: Reviewed, Reviews requested

#255 Dev to Master
  public/assets/css/adminEvents.css
  public/assets/css/contact.css
  public/assets/css/home.css
  public/assets/css/listinfo.css
  public/assets/css/thanks.css
  src/Controller/ContactController.php
  src/View/About/index.html.twig
  src/View/Admin/Activity/_form.html.twig
  src/View/Admin/Activity/add.html.twig
  src/View/Admin/Activity/edit.html.twig
  src/View/Admin/Activity/index.html.twig
  src/View/Admin/Board/_form.html.twig
  src/View/Admin/Board/index.html.twig
  src/View/Admin/Event/_form.html.twig
  src/View/Admin/Event/add.html.twig
  src/View/Admin/Event/edit.html.twig
  src/View/Admin/Event/index.html.twig
  src/View/Admin/Information/_form.html.twig
  src/View/Admin/Information/index.html.twig
  src/View/Components/_navbar.html.twig
  src/View/Contact/_form.html.twig
  src/View/Contact/index.html.twig
  src/View/Contact/thanks.html.twig
  src/View/Home/activity.html.twig
  src/View/Home/index.html.twig
  src/View/Home/informations.html.twig
  src/View/layoutAdmin.html.twig
Labels: Reviewed
